name: Docker Image CI

on: 
  workflow_dispatch:
      inputs:
            fullBuild:
              description: 'Run a full build'
              type: boolean
              required: false
              default: false
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
